### PR TITLE
use `?` instead of `try!`

### PR DESCRIPTION
**Pull request by froydnj**
Time to drag this crate to a more modern Rust style.

### CODE REVIEW

**Comment by luser** [comment]
I invited you as a collaborator so you can merge this and any future changes yourself. It looks like the Windows builds are broken, it'd be good to figure out what's up there before merging. (I'm also open to moving this repo to the Mozilla org if that'd be helpful.)

**Comment by froydnj** [comment]
Thanks for the invite!  It looks like the appveyor configuration is somehow stuck on Rust 1.16 as stable.  Being completely unfamiliar with this, I'm tempted to just cargo-cult sccache's Rust appveyor setup into makecab and see whether that fixes things; maybe I should do that as a separate PR.

**Comment by luser** [comment]
Maybe it's some weird caching or something like that? In that case it seems fine to merge this PR and see what happens in CI.

**Comment by luser** [comment]
The AppVeyor nightly build is failing tests which seems like a real issue. Also, a while back I found that someone has written [a much more full-featured cab crate](https://docs.rs/cab/0.2.0/cab/). It might be better in the long-term to rip my implementation out of this crate and make it just a CLI that invokes that crate instead? It'd be much less code, for sure.

**Comment by froydnj** [comment]
> Maybe it's some weird caching or something like that? In that case it seems fine to merge this PR and see what happens in CI.

The script in `appveyor_rust_install.pml` is getting things directly from `static.rust-lang.org` rather than going through `rustup`, so maybe there were some changes with how `static.rust-lang.org` was organized around that time?  I don't see anything in the [Rust 1.17 release notes](https://github.com/rust-lang/rust/blob/master/RELEASES.md#version-1170-2017-04-27), though...

**Comment by luser** [comment]
In any event I appear to have cribbed that setup code from this repo, whose setup has changed since then:
https://github.com/starkat99/appveyor-rust/blob/e14bc006cfdd643df27a4ec4553d96dc963ec390/appveyor.yml#L105

You could probably update it to use that instead.

**Comment by luser** [comment]
Or not, honestly, I'm not that hung up on it and as long as you can validate things in Mozilla CI that's fine. If you wanted to just vendor this repo into m-c and call that the canonical source and use Taskcluster feel free to do so.

**Comment by luser** [comment]
Closing in favor of #4

**Pull request closed without merging**
